---
- name: Remove old Docker versions and containerd
  apt:
    name: "{{ packages }}"
    state: absent
    purge: yes
    autoremove: yes
  vars:
    packages:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - containerd.io
      - runc

- name: Install prerequisites
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - net-tools

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker Engine and containerd
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Set docker.sock permissions
  file:
    path: /var/run/docker.sock
    mode: "0666"