---
# File: pulumi_IaC/ansible/roles/frontend/tasks/main.yml
# Fixed to use container-based dynamic nginx configuration

- name: Display deployment info
  debug:
    msg: |
      🚀 Starting SimplyDone Frontend Deployment
      ALB DNS: {{ alb_dns }}
      Frontend Host: {{ ansible_host }}

- name: Wait for Docker to be available
  wait_for:
    path: /var/run/docker.sock
    state: present
    timeout: 60

- name: Install required packages
  apt:
    name:
      - python3-docker
      - python3-pip
      - curl
      - jq
      - net-tools
    state: present
    update_cache: true

- name: Verify ALB connectivity before deployment
  uri:
    url: "http://{{ alb_dns }}/health"
    method: GET
    timeout: 30
  register: alb_health_check
  retries: 5
  delay: 10
  ignore_errors: true

- name: Display ALB health status
  debug:
    msg: "ALB Health: {{ 'OK' if alb_health_check.status == 200 else 'Failed - Will continue deployment' }}"

- name: Create application directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
  loop:
    - /opt/simply-done
    - /var/log/simply-done

- name: Stop existing frontend container
  docker_container:
    name: simply-done-client
    state: absent
  ignore_errors: true

- name: Remove old frontend images for clean deployment
  docker_image:
    name: bayajid23/simply-done-client
    state: absent
    force_absent: true
  ignore_errors: true

- name: Pull latest frontend image
  docker_image:
    name: bayajid23/simply-done-client:latest
    source: pull
    force_source: true

- name: Start frontend container with ALB configuration
  docker_container:
    name: simply-done-client
    image: bayajid23/simply-done-client:latest
    state: started
    restart_policy: always
    ports:
      - "80:80"
    volumes:
      - /var/log/simply-done:/var/log/nginx
    env:
      BACKEND_ALB_DNS: "{{ alb_dns }}"
      BACKEND_URL: "{{ alb_dns }}"
      DEPLOYMENT_ENV: "production"
      NGINX_WORKER_PROCESSES: "auto"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/nginx-health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    log_driver: "json-file"
    log_options:
      max-size: "10m"
      max-file: "3"
  register: container_status

- name: Wait for container to be healthy
  wait_for:
    host: localhost
    port: 80
    timeout: 120
    state: started
  when: container_status.changed

- name: Test frontend homepage
  uri:
    url: "http://localhost/"
    method: GET
    timeout: 15
  register: frontend_test
  retries: 5
  delay: 5

- name: Test API proxy functionality through ALB
  uri:
    url: "http://localhost/health"
    method: GET
    timeout: 20
  register: api_proxy_test
  retries: 5
  delay: 3
  ignore_errors: true

- name: Get container logs for debugging
  shell: docker logs --tail 20 simply-done-client
  register: container_logs
  changed_when: false

- name: Display deployment summary
  debug:
    msg: |
      ✅ FRONTEND DEPLOYMENT COMPLETE!
      
      🌐 Frontend Status: {{ 'Healthy' if frontend_test.status == 200 else 'Check needed' }}
      🔗 API Proxy Status: {{ 'Working' if api_proxy_test.status == 200 else 'Needs verification' }}
      🏗️ Backend ALB: {{ alb_dns }}
      📦 Container: {{ container_status.container.Id[:12] if container_status.container is defined else 'Check status' }}
      
      🧪 Test URLs:
      Frontend: http://{{ ansible_host }}/
      API Health: http://{{ ansible_host }}/health
      Direct Backend: http://{{ alb_dns }}/health

- name: Show container environment variables
  shell: docker exec simply-done-client env | grep -E "(BACKEND|ALB)"
  register: container_env
  changed_when: false
  ignore_errors: true

- name: Display container environment
  debug:
    msg: "Container Environment: {{ container_env.stdout_lines if container_env.stdout_lines else ['No backend env vars found'] }}"

- name: Show recent container logs
  debug:
    msg: "Recent logs: {{ container_logs.stdout_lines[-10:] if container_logs.stdout_lines else ['No logs available'] }}"

- name: Verify container nginx configuration
  shell: docker exec simply-done-client cat /etc/nginx/conf.d/default.conf | grep -E "(proxy_pass|server_name)"
  register: nginx_config_check
  changed_when: false
  ignore_errors: true

- name: Display nginx configuration verification
  debug:
    msg: "Nginx Config Check: {{ nginx_config_check.stdout_lines if nginx_config_check.stdout_lines else ['Could not verify nginx config'] }}"