version: "3.8"

services:
  backend:
    image: bayajid23/simply-done-server:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - ACCESS_TOKEN_SECRET=mySecret
      - ACCESS_TOKEN_EXPIRES_IN=12h
    restart: unless-stopped

  frontend:
    image: bayajid23/simply-done-client:latest
    ports:
      -  "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
