---
- name: Install and Configure MongoDB
  hosts: mongodb
  become: yes
  tasks:
    - name: Remove conflicting packages
      apt:
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
        state: absent
        purge: yes
        autoremove: yes

    - name: Wait for cloud-init to finish
      command: cloud-init status --wait

    - name: Update package list
      apt:
        update_cache: yes

    - name: Install prerequisites
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create data directory
      file:
        path: /data/db
        state: directory
        mode: "0755"

    - name: Run MongoDB container
      docker_container:
        name: mongodb
        image: mongo:latest
        state: started
        restart_policy: always
        ports:
          - "27017:27017"
        volumes:
          - /data/db:/data/db

    - name: Register MongoDB IP
      set_fact:
        mongodb_ip: "{{ ansible_host }}"
      delegate_to: localhost
      delegate_facts: true

    - name: Output MongoDB IP
      debug:
        msg: "MongoDB is running at {{ ansible_host }}"